name: Daily Random GIF every 5 mins

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download Random GIF
      id: download-random-gif
      run: |
        echo output-gif=$(python main.py --search ${{ vars.SEARCH_KEY }} --api-key ${{ secrets.TENOR_API_KEY }} | grep -oP "https://media.tenor.com/.*/\K.*") >> $GITHUB_OUTPUT
    - name: Commit new GIF
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '🌟 feat: 🤖 upload new GIF ${{ steps.download-random-gif.outputs.output-gif }}'
        file_pattern: '*.gif'
